apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zed-web-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zed-pkg/zed-infra.git
    targetRevision: main
    path: k8s/manifests/zed-web-server/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: zed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
